export enum AutoPowerOffWearingDetection {
    POWER_OFF_IN_5_MIN = 0,
    POWER_OFF_IN_30_MIN = 1,
    POWER_OFF_IN_60_MIN = 2,
    POWER_OFF_IN_180_MIN = 3,
    POWER_OFF_IN_15_MIN = 4,
    POWER_OFF_WHEN_REMOVED_FROM_EARS = 16,
    POWER_OFF_DISABLE = 17
}