export enum PowerInquiredType {
    BATTERY = 0,
    LEFT_RIGHT_BATTERY = 1,
    CRADLE_BATTERY = 2,
    POWER_OFF = 3,
    AUTO_POWER_OFF = 4,
    AUTO_POWER_OFF_WEARING_DETECTION = 5,
    POWER_SAVE_MODE = 6,
    LINK_CONTROL = 7,
    BATTERY_WITH_THRESHOLD = 8,
    LR_BATTERY_WITH_THRESHOLD = 9,
    CRADLE_BATTERY_WITH_THRESHOLD = 10,
    BATTERY_SAFE_MODE = 11,
    CARING_CHARGE = 12,
    BT_STANDBY = 13
}