export enum VoiceGuidanceInquiredType {
    MTK_TRANSFER_WO_DISCONNECTION_NOT_SUPPORT_LANGUAGE_SWITCH = 0,
    MTK_TRANSFER_WO_DISCONNECTION_SUPPORT_LANGUAGE_SWITCH = 1,
    SUPPORT_LANGUAGE_SWITCH = 2,
    ONLY_ON_OFF_SETTING = 3,
    VOLUME = 32,
    VOLUME_SETTING_FIXED_TO_5_STEPS = 33,
}