export enum VoiceGuidanceLanguage {
    UNDEFINED_LANGUAGE = 0,
    ENGLISH = 1,
    FRENCH = 2,
    GERMAN = 3,
    SPANISH = 4,
    ITALIAN = 5,
    PORTUGUESE = 6,
    DUTCH = 7,
    SWEDISH = 8,
    FINNISH = 9,
    RUSSIAN = 10,
    JAPANESE = 11,
    BRAZILIAN_PORTUGUESE = 13,
    KOREAN = 15,
    TURKISH = 16,
    CHINESE = 240,
}