export enum NcAsmInquiredType {
    NC_ON_OFF = 1,
    NC_ON_OFF_AND_ASM_ON_OFF = 17,
    NC_MODE_SWITCH_AND_ASM_ON_OFF = 18,
    NC_ON_OFF_AND_ASM_SEAMLESS = 19,
    NC_MODE_SWITCH_AND_ASM_SEAMLESS = 20,
    MODE_NC_ASM_AUTO_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 21,
    MODE_NC_ASM_DUAL_SINGLE_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 22,
    MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 23,
    MODE_NC_NCSS_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS = 24,
    MODE_NC_ASM_DUAL_NC_MODE_SWITCH_AND_ASM_SEAMLESS_NA = 25,
    ASM_ON_OFF = 33,
    ASM_SEAMLESS = 34,
    NC_AMB_TOGGLE = 48,
    NC_TEST_MODE = 64
}