export enum LEAInquiredType {
    TWS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 0,
    HBS_SUPPORTS_A2DP_LEA_UNI_LEA_BROAD_WITH_CTKD = 1,
    TWS_SUPPORTS_LEA_UNI_LEA_BROAD = 2,
    CLASSIC_ONLY_LE_CLASSIC_SETTING = 12,
    EXECUTE_TANDEM_TARGET_CHANGE = 13,
    CHANGE_TANDEM_CONNECTION_PROFILE_FOR_ANDROID = 14,
    BGM_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 245,
    HEAD_TRACKER_CANT_BE_USED_WITH_LEA_CONNECTION = 246,
    PAIRING_DEVICE_MANAGEMENT_CANT_BE_USED_WITH_LEA_CONNECTION = 247,
    SOUND_AR_CANT_BE_USED_WITH_LEA_CONNECTION = 248,
    AUTO_PLAY_CANT_BE_USED_WITH_LEA_CONNECTION = 249,
    GATT_CONNECTABLE_CANT_BE_USED_WITH_LEA_CONNECTION = 250,
    SOUND_AR_OPTIMIZATION_CANT_BE_USED_WITH_LEA_CONNECTION = 251,
    QUICK_ACCESS_CANT_BE_USED_WITH_LEA_CONNECTION = 252,
    CONNECTION_MODE_CANT_BE_USED_WITH_LEA_CONNECTION = 253,
    VOICE_ASSISTANT_SETTINGS_CANT_BE_USED_WITH_LEA_CONNECTION = 254,
    VOICE_ASSISTANT_WAKE_WORD_CANT_BE_USED_WITH_LEA_CONNECTION = 255
}