export enum PeripheralInquiredType {
    PAIRING_DEVICE_MANAGEMENT_CLASSIC_BT = 0,
    SOURCE_SWITCH_CONTROL_CLASSIC_BT = 1,
    PAIRING_DEVICE_MANAGEMENT_WITH_BLUETOOTH_CLASS_OF_DEVICE_CLASSIC_BT = 2
}