export enum PeripheralResult {
    DISCONNECTION_SUCCESS = 0,
    DISCONNECTION_ERROR = 1,
    DISCONNECTION_IN_PROGRESS = 2,
    DISCONNECTION_BUSY = 3,
    CONNECTION_SUCCESS = 16,
    CONNECTION_ERROR = 17,
    CONNECTION_IN_PROGRESS = 18,
    CONNECTION_BUSY = 19,
    UNPAIRING_SUCCESS = 32,
    UNPAIRING_ERROR = 33,
    UNPAIRING_IN_PROGRESS = 34,
    UNPAIRING_BUSY = 35,
    PAIRING_SUCCESS = 48,
    PAIRING_ERROR = 49,
    PAIRING_IN_PROGRESS = 50,
    PAIRING_BUSY = 51
}