export enum AlertInquiredType {
    FIXED_MESSAGE = 0,
    VIBRATOR_ALERT_NOTIFICATION = 1,
    FIXED_MESSAGE_WITH_LEFT_RIGHT_SELECTION = 2,
    VOICE_ASSISTANT_ALERT_NOTIFICATION = 3,
    APP_BECOMES_FOREGROUND = 4,
    LE_AUDIO_ALERT_NOTIFICATION = 5,
    FLEXIBLE_MESSAGE = 6
}